import bcrypt


# A salt is generated by the bcrypt library. The bcrypt library (should) store the salt information within
# the hash itself. See https://stackoverflow.com/questions/9594125/salt-and-hash-a-password-in-python

def hash_pwd(pwd):
    return bcrypt.hashpw(pwd.encode("utf-8"), bcrypt.gensalt())


def check_pwd(pwd, hashed_pwd):
    return bcrypt.checkpw(pwd, hashed_pwd)
