from bcrypt import hashpw, gensalt, checkpw


# A salt is generated by the bcrypt library. The bcrypt library (should) store the salt information within
# the hash itself. See https://stackoverflow.com/questions/9594125/salt-and-hash-a-password-in-python


def hash_pwd(pwd):
    return hashpw(pwd.encode("utf-8"), gensalt())


def compare_pwd(pwd, hashed_pwd):
    return checkpw(pwd.encode("utf-8"), hashed_pwd.encode("utf-8"))


