SERVER_HOST_NAME = 'localhost'
SERVER_PORT = 5050

HEADER = 64
FORMAT = 'utf-8'
GET_PUBLIC_KEY = '!GETRSA'
CREATE_ENCR_AES_KEY = '!GETENCRAES'
SERVER_SEND_ENCRYPTED_AES_KEY = '!SERVERSENDKEY'
START_ENCRYPTION = '!AES_START'
STOP_ENCRYPTION = '!AES_STOP'
SEND_CONVERSATION_ID = '!SEND_USER'
NO_ENCRYPTION = '!NOCRYPT'
BACK_COMMAND = "!BACK"
CRYPTED_CONTENT = '!CRYPTOGRAHIC'

